name: Build Docker Image - Branch

on:
  push:
    paths-ignore:
    - '**/.github*'
    - '**/LICENSE'
    - '**/NOTICE'
    - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Branch name
      id: branch_name
      run: echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
     
    - name: Build and export
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        tags: hubok/nginx-alpine:$SOURCE_BRANCH
        outputs: type=oci,dest=/tmp/image.tar
      env: 
        SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
