name: Build Docker Image

on:
  push:
    paths-ignore:
    - '**/LICENSE'
    - '**/NOTICE'
    - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: GitHub REF Data
      id: github_ref
      run: |
        echo ::set-output name=SOURCE::${GITHUB_REF##*/}
        echo ${GITHUB_REF}
        echo ${GITHUB_REF##*/}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build, export, and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: true
        outputs: type=docker,dest=/tmp/image.tar
        tags: |
          hubok/nginx-alpine:${{ steps.github_ref.outputs.SOURCE }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: /tmp/image.tar

    - name: Update DockerHub repo description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: hubok/nginx-alpine
